### ISSUE TITLE
problem retriving data

### ISSUE THREAD

**Issue by Ajking11** [Sage/SData-2.0#35] opened 2015-11-11 08:30 UTC
Hi guys,
 could some one shead so light on an issue im having retrieving the commodities. when i issue the following link, http:/127.0.0.1:5493/sdata/accounts50/GCRM/-/commodities.

im retrieving this back:
`<diagnosis xmlns="http://schemas.sage.com/sdata/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:http="http://schemas.sage.com/sdata/http/2008/1">
<sdata:severity>error</sdata:severity>
<sdata:sdataCode>ApplicationDiagnosis</sdata:sdataCode>
<sdata:applicationCode/>
<sdata:message>
GET operation failed - ERROR [42000] Syntax error: Invalid order specification at System.Data.Odbc.OdbcConnection.HandleError(OdbcHandle hrHandle, RetCode retcode) at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader, Object[] methodArguments, SQL_API odbcApiMethod) at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader) at System.Data.Odbc.OdbcCommand.ExecuteScalar() at Sage.Integration.Accounts50.SDOAdapter.Feeds.commodityFeedEntry.GetCompleted(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.SDORequestHandler.OnPostCreateEntry(IRequest request, IOdbcDataReader dataReader, Company company, FeedEntry feedEntry, Object primaryKey) at Sage.Integration.Accounts50.SDOAdapter.SDORequestHandler.OnGetRequest(IRequest request, IFeed feed) at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnGetRequest(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.GetRequest(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.OnGetResource(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.GetRequest(IRequest request) (-1)
</sdata:message>
<sdata:stackTrace/>
<sdata:payloadPath/>
</diagnosis>`

any ideas.

**Comment by darroncockram** [comment] 2015-11-11 11:00
Not one I've seen before. Are you sure that's definitely the URL being used in the request?

**Comment by Ajking11** [comment] 2015-11-11 14:46
yeah, ive tracked the error down to records 1203 to 1207. but unsure how to fix the problem. i've re indexed the databases but to no avail.

**Comment by darroncockram** [comment] 2015-11-11 19:11
>yeah, ive tracked the error down to records 1203 to 1207. but unsure how to fix the problem. i've re indexed the databases but to no avail.

When you say 1203 and 1207 are you referring to stock codes in the Accounts dataset? How have you identified these records as being the cause of the error?

If you do have data corruption then reindexing won't make a difference to that I'm afraid. Data repair is off topic for the Sdata forums but if you do have corruption best bet would be to contact the Accounts support team to discuss how best to correct the problem. Unfortunately as long as you have corruption there'd be no guarantee that the Sdata feeds would function correctly.

**Comment by darroncockram** [comment] 2015-11-16 07:33
Closing issue as apparently not related to Sdata

**Closed by darroncockram** 2015-11-16 07:33 UTC
