### ISSUE TITLE
Posting Nominal Code to salesorderline in Sage 50

### ISSUE THREAD

**Issue by asterix187** [Sage/SData-2.0#32] opened 2015-11-09 16:44 UTC
It appears that when you try to post the nominal code when posting a salesorderline the nominal code does not get set. I have tried posting it as a financialaccount against the line as this doesn't work either.

There is a nominalcode field against salesorderline that doesn't show the nominal code when reading or allows it to set when writing.

**Comment by darroncockram** [comment] 2015-11-09 19:51
The nominalCode field implies that you are referencing the Accounts assemblies directly which isn't supported. That field is meant to be an internal-only field and not intended to be exposed, which is why you won't see any reference to it in the schema.

The nominal code follows the same rules as the main Accounts application and will be set to the appropriate default value based on the settings on the line type, associated commodity and customer. It should be possible to override this however and the financialAccounts property would be the correct way to do so but I've just tested this and the code isn't being overridden so I'll raise this with the Accounts team.

**Comment by AlbrightPatents** [comment] 2016-05-24 18:57
Has this been fixed yet? I really need to get nominals into a sales invoice. Thanks Sarah

**Comment by darroncockram** [comment] 2016-05-25 08:04
Afraid not.

**Comment by apathytomorrow** [comment] 2016-09-19 13:18
Is there any updates on this? The SData service doesn't seem to provide nominal codes. :(

**Comment by darroncockram** [comment] 2016-10-03 08:10
The Accounts Sdata adapter does provide nominal codes (it's the financialAccounts feed). The issue is that you cannot set the financialAccount on a salesInvoice,  or more specifically that it is overridden if you do. The issue is still with the Accounts team but there's no ETA on it being addressed I'm afraid.

**Comment by darroncockram** [comment] 2018-10-05 15:39
Just heard that this has been fixed in as of v24.2 of Sage 50 Accounts

**Closed by darroncockram** 2018-10-05 15:39 UTC

**Comment by asterix187** [comment] 2018-10-05 15:42
Great thanks Darron! Both for the facts you have found out, its fixed and it indicates that someone somewhere is at least making minor changes to sData!
