### ISSUE TITLE
Sage 50 Cloud Account - SData 2.0 random xml errors when Get on Windows 10

### ISSUE THREAD

**Issue by timtitch** [Sage/SData-2.0#143] opened 2019-11-22 12:47 UTC
Hi
Since installing new Windows 10 Pro client machine with our app (our Windows app has not changed) clients are experiencing random xml errors from the sdata 2.0 feed with Sage 50 Cloud Accounts . Worked fine when running on windows 7 or Server 2012.
The xml errors vary such as "elements not closed" or "unexpected end of file" when we interrogate sage for product codes or lists of invoices for example - but not every time.
If they try several times it may eventually work.
Windows Pc is fully updated, plenty of ram and disk space

Any ideas please?

Thanks, Tim

Timestamp: 21/10/2019 10:44:12

Message: HandlingInstanceID: 65ebcd99-40b2-4f3d-b0c6-74f6544ba819
An exception of type 'System.ApplicationException' occurred and was caught.
---------------------------------------------------------------------------
10/21/2019 11:44:12
Type : System.ApplicationException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 Message : Sage Product Code W50 is missing from Sage. Please add it to Sage and try again.
Source : SETS.WinForms
Help link : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Int32 CreateInvoices2(Boolean, System.Text.StringBuilder) HResult : -2146232832
Stack Trace :    at SETS.WinForms.Components.InvoicePreviewComponent.CreateInvoices2(Boolean Preview, StringBuilder sb)
   at SETS.WinForms.Components.InvoicePreviewComponent.CreateInvoices(Boolean Preview, Boolean IncludeECD, Boolean IncludeLifts, Boolean IncludeStorageCosts)
   at Atlas.HilaireCRM.InvoicePreview.InvoicesBackgroundWorker_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

Additional Info:

MachineName : SETS-9XRZKT2
TimeStamp : 21/10/2019 10:44:12
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=5.0.414.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 AppDomainName : Atlas.HilaireCRM.exe ThreadIdentity : SETS\account WindowsIdentity : SETS\account
	Inner Exception
	---------------
	Type : System.Xml.XmlException, System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
	Message : Unexpected end of file has occurred. The following elements are not closed: entry, feed. Line 161, position 4.
	Source : System.Xml
	Help link : 
	LineNumber : 161
	LinePosition : 4
	SourceUri : 
	Data : System.Collections.ListDictionaryInternal
	TargetSite : Void Throw(System.Exception)
	HResult : -2146232000
	Stack Trace :    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
	   at System.Xml.XmlTextReaderImpl.ThrowUnclosedElements()
	   at System.Xml.XmlTextReaderImpl.ParseElementContent()
	   at Sage.Common.Metadata.RuntimeObjectXmlReader.XmlAttributeReader.Read()
	   at Sage.Common.Metadata.RuntimeObjectXmlReader.XmlAttributeReader.Read()
	   at Sage.Common.Metadata.RuntimeObjectXmlReader.SkipWhitespace(XmlReader reader)
	   at Sage.Common.Metadata.RuntimeObjectXmlReader.ReadReferenceList[S,T](XmlReader reader, String containerName, String itemName, ISerializationSettings settings)
	   at ObjectXmlReader1d1286e2a07745ec8df4a475521e3ec9.dll.ReadElement(XmlReader , Object , Int32 , ISerializationSettings )
	   at Sage.Common.Metadata.RuntimeObjectXmlReader.ReadReference[T](XmlReader reader, T component, String name, ISerializationSettings settings)
	   at ObjectXmlReader1d1286e2a07745ec8df4a475521e3ec9.dll.Deserialize(XmlReader , Object , String , ISerializationSettings )
	   at Sage.Common.Metadata.RuntimeObjectXmlReader.ReadReferenceElement[S,T](XmlReader reader, T component, ISerializationSettings settings)
	   at Sage.Common.Metadata.RuntimeObjectXmlReader.ReadReferenceList[S,T](XmlReader reader, String containerName, String itemName, ISerializationSettings settings)
	   at ObjectXmlReader576af42cdfcd4ead917987b28937db81.dll.ReadElement(XmlReader , Object , Int32 , ISerializationSettings )
	   at Sage.Common.Metadata.RuntimeObjectXmlReader.ReadReference[T](XmlReader reader, T component, String name, ISerializationSettings settings)
	   at ObjectXmlReader576af42cdfcd4ead917987b28937db81.dll.Deserialize(XmlReader , Object , String , ISerializationSettings )
	   at Sage.Common.Metadata.RuntimeObjectXmlReader.Deserialize(XmlReader reader, Object component)
	   at Sage.Common.Syndication.FeedSerializer.LoadFromStream[T](Feed`1 feed, Stream stream, ISerializationSettings settings, String assemblyFileLocation)
	   at Sage.Common.Syndication.FeedSerializer.LoadFromStream[T](Feed`1 feed, Stream stream, ISerializationSettings settings)
	   at Sage.Common.Syndication.FeedSerializer.LoadFromStream[T](Feed`1 feed, Stream stream)
	   at Sage.Integration.Client.SDataRequest.RequestFeed[T](Feed`1 feed)
	   at SETS.BusinessLayer.SData.FeedExtensions.Get[T](Feed`1 feed, Expression`1 predicate)
	   at SETS.BusinessLayer.SData.SDataQuery.Get[T](Expression`1 predicate)
	   at SETS.WinForms.Components.InvoicePreviewComponent.CreateInvoices2(Boolean Preview, StringBuilder sb)

**Comment by darroncockram** [comment] 2019-11-25 08:47
Not one I've come across before. I'm running Windows 10 and the Sdata feeds are working OK for me, so it's not specifically a Windows 10 problem.

From the error message it is fairly clear that the problem is happening when attempting to parse XML of the response from the server. I don't think the un-closed element is the real issue as the XML generation on the server is entirely automated so it's not possible for it to miss closing a tag in the XML. I suspect that the error is actually just symptom of the real problem. 

The red flag for me is the "Unexpected end of file has occurred" error . I suspect that what is happening is the the response is being truncated for some reason so the client is not getting the full XML so the XML parser fails on the client. My guess would be that the response size is hitting some limit and getting truncated. This might also help to explain the random nature of the problem as whether or not the truncation happens would be dependent on the actual data being returned so some requests may be small enough to not be truncated and would process OK whilst others are too big and would fail.

If this is the case then it would lead to the questions what is imposing the limit and why is it different on Windows 10? That I'm not so sure on but it would be worth seeing if it is possible to reduce the size of the response payload to see if that makes a difference. 

I'm not sure what queries are being sent to the Sdata service at the point the error is generated but in terms of reducing the payload I have a few tips:
- If retrieving collection data look at using paging to limit how much data is returned in a single request.
- Limit or remove the use of includes
- If you are not displaying the raw response then specify the (undocumented) _includeContent parameter with a value of false on the request URL. If you are using the SIF then you can do this by simply setting the IncludeContent property of the SdataUri to false.

Hope that helps.

**Comment by timtitch** [comment] 2019-12-03 11:44
Hi Darron thanks

to be honest the data size I'm getting is pretty small, it's just the irregularity of the failures that's a puzzle.

In the end I modified the GetFeed call and placed a retry with a 1 second delay between calls if it fails. This seems to have fixed the problem for the user on Windows 10.

We do call the feed in a loop to ensure product codes exist, maybe 10 codes max one after the other, could that be causing issues with the feed?

I did manually enter the url thats used in the GetFeed call into a browser on the users PC and that always worked although of course there would a second or so delay between each browser refresh but it never errored.

Cheers

**Comment by darroncockram** [comment] 2019-12-04 07:07
To test the theory that contention might be causing the problem I ran a test of sending a request from 10 separate threads to concurrently retrieve a single commodity, but I didn't see any errors with that. Even upping it to 50 threads doesn't seem to cause a problem (although it's not as quick as I'd hoped it would be).

Given the error message you are seeing it suggests the request is being received an processed OK by the server. It would seem that the problem is either on serialising the response on the server or with the client receiving/processing the response. I'm at a bit of a loss to explain what could be causing such a problem though. The retry pattern you have implemented sounds like a reasonable workaround at least.

**Closed** 2019-12-09 06:48 UTC
